- name: download flyway
  get_url: url=https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/4.2.0/flyway-commandline-4.2.0-linux-x64.tar.gz dest=/root/flyway.tar.gz

- name: unpack flyway
  unarchive: remote_src=yes src=/root/flyway.tar.gz dest=/opt

- name: create a symlink
  file: state=link src=/opt/flyway-4.2.0 dest=/opt/flyway

- name: put a config file
  template: src=flyway.conf dest=/opt/flyway/conf/flyway.conf backup=yes
